### ISSUE TITLE
How about releasing a version compatible with OCaml 4.08.1 on opam?

### ISSUE THREAD

**Issue by jrochel** [alainfrisch/gen_js_api#100]

**Comment by Lupus** [comment]
I was looking for 4.08.1 compatible release as well! Support is already in master IIRC.

**Comment by Lupus** [comment]
@mlasson how are your plans on releasing fresh version of gen_js_api? Friendly ping :)

**Comment by mlasson** [comment]
It has been done last week. If you do opam update you should have 1.6.0 available and it compiles above 4.08. Re-open the issue if you have any problem !

**Comment by Lupus** [comment]
Oh, sorry, my bad, I didn't notice latest tag, as it differs in formatting. Thanks!

![image](https://user-images.githubusercontent.com/105348/83402861-3a229b80-a410-11ea-8522-5567984e111f.png)

**Comment by mlasson** [comment]
It was my bad, I did not publish it on github :/.

**Comment by Lupus** [comment]
Lol, I indeed though that I missed the v1.0.6 tag :D Great we have it sorted out now!
