### ISSUE TITLE
Allow to run ppxlib deriving and gen_js_api ppx together   

### ISSUE THREAD

**Issue by hhugo** [alainfrisch/gen_js_api#107]
One currently cannot use ppxlib deriving together with gen_js_api.
In particular, running the code bellow will fail with `Error: Cannot parse signature item`
```ocaml
module M : sig 
  type t = { a : int; b : string } [@@deriving sexp]
  val t_of_js : Ojs.t -> t
  val t_to_js : t -> Ojs.t
end = [%js]
```

The reason is that ppxlib will expand deriving first and then run the gen_js_api mapper, at which point `[@@deriving sexp]` has generated item that gen_js_api doesn't understand (e.g. `include`). 

One could imagine the following steps instead:
1. expand gen_js_api first
```ocaml
module M : sig 
  type t = { a : int; b : string } [@@deriving sexp]
  val t_of_js : Ojs.t -> t
  val t_to_js : t -> Ojs.t
end = struct
  type t = { a : int; b : string } [@@deriving sexp]
  let t_of_js = ....
  let t_to_js = ....
end
```
2. then apply deriving
```ocaml
module M : sig 
  type t = { a : int; b : string }
  include sig
    [@@@ocaml.warning "-333"]
     val t_of_sexp : sexp -> t
     val sexp_of_t : t -> sexp
  end 
  val t_of_js : Ojs.t -> t
  val t_to_js : t -> Ojs.t
end = struct
  type t = { a : int; b : string }
  let t_of_sexp = .....
  let sexp_of_t = .....
  let t_of_js = ....
  let t_to_js = ....
end
```

Talking with @jeremiedimino, there are two approaches to explore:
- making gen_js_api register a `Context_free.Rule.t` instead of whole AST mapper. That might require changing the syntax a little 
- allow to specify some kind of ordering between AST mappers

**Comment by nojb** [comment]
I discussed this with @jeremiedimino just now. We agreed that trying trying to customize the ordering of the ppx is ad-hoc and not very robust. Changing the syntax to make it possible to define a "local" ppx rewriter seems the better option. We need to discuss this internally though. I will post back here with any updates.

**Comment by hhugo** [comment]
Can you reopen this one ? It's not fully addressed yet.

**Comment by nojb** [comment]
Yes, sorry
