### ISSUE TITLE
 .ts -> mli converter 

### ISSUE THREAD

**Issue by zoggy** [alainfrisch/gen_js_api#11]
Hello,

Do you plan to add a .d.ts -> .mli converter ? (does it make sense ?)
This could be very useful to use declarations from https://github.com/borisyankov/DefinitelyTyped instead of writing all .mli file by hand.

**Comment by alainfrisch** [comment]
It would indeed make sense to (semi-)automate the creation of bindings from TypeScript interfaces.  This would force to hard-code choices of how concepts are mapped to OCaml, or to provide ways to specify this in a declarative way.  Also, it's not completely clear that TypeScript interfaces provide enough information (e.g. are they accurate w.r.t. nullability?), nor that they are correct.  But it's certainly an interesting direction.

For now, we are more interested in improving the tool and starting to use it manually.

**Comment by alainfrisch** [comment]
You might be interested in Andy Ray's work on parsing .ts declarations to produce OCaml bindings automatically:

  https://github.com/andrewray/DefinitelyMaybeTyped
  https://github.com/ocsigen/js_of_ocaml/issues/114

**Comment by zoggy** [comment]
Ok. And thanks for the links.

**Comment by aimkeepachieve** [comment]
If you want to convert TS video to MP4, AVI, MOV, DV, WMV etc format, you may refer to this guide at http://www.idealshare.net/video-converter/ts-converter-for-mac-or-windows.html
