### ISSUE TITLE
calling new on a dynamic value

### ISSUE THREAD

**Issue by joprice** [alainfrisch/gen_js_api#112]
Is it possible to call new on a constructor that is passed as an argument? Sometimes libraries have nested constructors that are only reachable after creating another object, and libraries loaded with "require" would not expose a global path to the constructor.

**Comment by mlasson** [comment]
would you have an example of such a library ?

**Comment by joprice** [comment]
I was seeing if the boilerplate of this wrapper around the electron apis could be replaced with gen_js_api: https://github.com/xvw/ocamlectron/blob/develop/lib/electron_plumbing/Struct.ml#L331. 

That wrapper specifically around BrowserWindow gets called with the constructor type that is defined here https://github.com/xvw/ocamlectron/blob/4bc80200f518a0d41a0488f6c14b27b78626ed78/lib/electron_plumbing/BrowserWindow.mli#L155, 

accessed as a property of the electron object here https://github.com/xvw/ocamlectron/blob/4bc80200f518a0d41a0488f6c14b27b78626ed78/lib/electron_plumbing/ElectronMain.mli#L9, 

which is loaded from a wrapper around "require" here https://github.com/xvw/ocamlectron/blob/1f8e4d10e5fc6ead5bfa8d9dfdc083c09c5e1c76/lib/electron_main/Electron.ml#L3

In js, it is typically imported or destructured like

```js
const {BrowserWindow} = require('electron');

const window = new BrowserWindow({...});
```

**Comment by cannorin** [comment]
Now this should be possible with #145. I didn't notice this issue back then 😅

**Comment by mlasson** [comment]
Let's close the issue then :) ! Thanks.
