### ISSUE TITLE
Codegen change for functions named "get" and "set"; was this intentional? 

### ISSUE THREAD

**Issue by TyOverby** [alainfrisch/gen_js_api#136]
I wrote an MLI that looked like this:

```ocaml
(** https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map *)
type ('a, 'b) t

val create : unit -> ('a, 'b) t [@@js.new "Map"]
val set : ('a, 'b) t -> 'a -> 'b -> unit
val get : ('a, 'b) t -> 'a -> 'b option
val delete : ('a, 'b) t -> 'a -> unit 
```

Where the functions `get`, `set`, and `delete` called the corresponding functions on the Map object.

Recently, after updating my version of gen_js_api, the code generation changed so that "get" and "set" were doing property accesses instead of function calls.

I found this PR https://github.com/LexiFi/gen_js_api/pull/132, but there is no mention of a breaking change, nor can I find any documentation about how to get back to the original behavior.

**Comment by nojb** [comment]
cc @mlasson

**Comment by mlasson** [comment]
You are right. May be we should remove "index_get/_set" from the automatic selection of attributes to preserve backward compatibility. 

Maybe, we should deprecate the whole idea of automatic selection of [@@js.*] attributes.
It is too fragile and not trivial to guess at a glance.

**Comment by TyOverby** [comment]
> Maybe, we should deprecate the whole idea of automatic selection of [@@js.*] attributes.

Put me firmly in the "no magic" camp!

**Comment by TyOverby** [comment]
What other function names could change behavior?

**Comment by mlasson** [comment]
> What other function names could change behavior?

I think "get/set" should be the only one. But I would not bet my hand on it.
Using the current "master" version, you will have warning for each "unannotated" declarations; you should use that to help you annotate all of them. 

I'm sorry for the inconvenience; but hopefully it will be the last time we suffer from this problem.
