### ISSUE TITLE
Resolve the ocaml-migrate-parsetree < "2.0.0" constraint

### ISSUE THREAD

**Issue by copy** [alainfrisch/gen_js_api#138]
It prevents gen_js_api from being installed at the same time as ocamlformat in a 4.12 switch, since ocamlformat since 0.17 has a ocaml-migrate-parsetree >= "2.1.0" constraint.

**Comment by rgrinberg** [comment]
This is a problem for us with the vscode plugin. @mlasson are there plans to resolve this soon?

cc @mnxn

**Comment by mlasson** [comment]
Yes, we will try to fix that as soon as possible, even on our side, it has begun to be an issue.
I think we will go down the "ppxlib" road in more idiomatic way and we will drop the explicit dependency to ocaml-migrate-parsetree.
