### ISSUE TITLE
Using polymorphic types with `js.custom` and `js.call` gives weak polymorphism error

### ISSUE THREAD

**Issue by zbaylin** [alainfrisch/gen_js_api#163]
I have a method I want to call on an object, and that method is polymorphic, i.e.
```
val foo : Ojs.t -> 'a list -> 'a -> t
```
I would also like to partially apply this method using a value I got from a `require`, so I tried to use `js.custom` like so:

```ocaml
val foo : 'a list -> 'a -> t
  [@@js.custom
    val foo_internal : Ojs.t -> 'a list -> 'a -> t
    [@@js.call "foo"]

    let foo : 'a list -> 'a -> t = foo_internal required
  ]
```

However, this produces a type error which complains that `foo` is weakly polymorphic:

```
Values do not match:
  val foo : '_a list -> '_a -> t
is not included in
  val foo : 'a list -> 'a -> t
```

Universally qualifying `foo` like so:
```ocaml
val foo : 'a list -> 'a -> t
  [@@js.custom
    val foo_internal : Ojs.t -> 'a list -> 'a -> t
    [@@js.call "foo"]

    let foo : 'a. 'a list -> 'a -> t = foo_internal required
  ]
```

also does not work because the generated `foo_internal` is less general:

```
Error: This definition has type 'a list -> 'a -> t
       which is less general than
         'a. 'a list -> 'a -> t
```

I think this can be fixed by universally qualifying the function generated by `js.call`, but that might cause other unintended issues.

**Comment by jchavarri** [comment]
We figured out that this could be solved by eta-expanding the function, e.g. 

```ocaml
let foo list item = foo_internal required list item
```

to help the compiler remove the weak types.

**Comment by mlasson** [comment]
Thanks for the report. 

@jchavarri is right; I don't think we will do anything to adress this issue; you'll have to eta-expand.
