### ISSUE TITLE
Module alias

### ISSUE THREAD

**Issue by eyyub** [alainfrisch/gen_js_api#53]
Hi !

Sorry if I'm missing something but, is there a way to do `module Foo = Lib_foo` in `.mli` files used to bind a javascript lib ?
Actually `gen_js_api` throws an error, maybe it's a wanted behavior ?

Thanks

**Comment by alainfrisch** [comment]
Hi,

This is currently not supported out of the box, but you can always do:

``` ocaml
[@@@js.stop]
 module Foo = Lib_foo
[@@@js.start]
[@@@js.implem module Foo = Lib_foo]
```

**Comment by eyyub** [comment]
Thanks !
