### ISSUE TITLE
Question about ocaml version.

### ISSUE THREAD

**Issue by jordwalke** [alainfrisch/gen_js_api#54]
This project looks really great. I'm curious, why does it only support `4.03` and above?

**Comment by alainfrisch** [comment]
Most syntactic tools such as ppx are tied to a specific version of OCaml because the definition of the parse tree changes from one version to the other.  It shouldn't be too hard to adapt gen_js_api to work with older versions.  Do you have a specific use case in mind?

**Comment by jordwalke** [comment]
Ah, okay - I was mostly curious. `gen_js_api` is pretty forward looking, so I find it totally reasonable that you're focusing your efforts on the upcoming versions.
