### ISSUE TITLE
How to use js_of_ocaml types?

### ISSUE THREAD

**Issue by slegrand45** [alainfrisch/gen_js_api#56]
For instance, when the first parameter of a JS constructor is a DOM element, what is the way to use the jsoo type `Dom_html.element` for this parameter?

Trying something like:

``` ocaml
class foo : div:Dom_html.element -> _foo [@@js.new "..."]
```

gives

```
Error: Unbound value Dom_html.element_to_js
```

Is there any example available for this kind of binding? Thanks.

**Comment by alainfrisch** [comment]
gen_js_api does not currently have any special support for "js_of_ocaml types" (our own use case for gen_js_api does not involve any of js_of_ocaml native standard library or FFI).

What you can do is to define an abbreviation for `Dom_html.element` and provide the pair of {to_js, of_js} functions for it:

``` ocaml
type t = Dom_html.element
let t_to_js : t -> Ojs.t = Obj.magic
let t_of_js : Ojs.t -> t = Obj.magic
```

and then use this type in place of `Dom_html.element`.

**Comment by slegrand45** [comment]
Ok, i got it. Thank you very much for your answer.
