### ISSUE TITLE
[@@js.meth "..."] gives "Error: Spurious js.* attribute"

### ISSUE THREAD

**Issue by slegrand45** [alainfrisch/gen_js_api#57]
Does it mean that `js.meth` is deprecated and that `js.call` have to be used instead? If so, the method binding section in https://github.com/LexiFi/gen_js_api/blob/master/CLASSES.md should be updated because the code example for a method call uses `js.meth`.

**Comment by alainfrisch** [comment]
Indeed, this is `js.call`. Now fixed.  Thanks!
