### ISSUE TITLE
Problem using sum types

### ISSUE THREAD

**Issue by o-marshmallow** [alainfrisch/gen_js_api#58]
Hi !

I have been using gen_js_api for days and it works like a charm ! However, I am encountering a problem with sum types. Indeed, I created a file try.mli containing :
`type t =
  | Foo [@js "foo"]
  | Bar [@js 42]
  | Baz
    [@@js.enum]` 
(It's the example given in the documentation)

When I compile it (with all the commands given), the command
 `ocamlfind ocamlc -c -package gen_js_api.ppx try.ml` returns the error :
`File "try.ml", line 4, characters 10-12:
Error: Spurious js.* attribute`

In fact, the `.ml` file still contains the annotations `[@js "foo"]`, `[@js 42]` and `[@@js.enum]`. If I remove then from the .ml file, then it compiles and works well. So is it normal to still have the annotations in the `.ml` file ?

Thanks

**Comment by sbriais** [comment]
Hello, thanks for your report.
A simple workaround is to remove the call to gen_js_api.ppx when compiling with ocamlc. 
We will fix that in the near future.
Cheers
Sébastien

**Comment by sbriais** [comment]
Just pushed a fix onto master.

**Comment by o-marshmallow** [comment]
It's working now, 
Thank you !

**Comment by sbriais** [comment]
Nice!
