### ISSUE TITLE
PPX Syntax in MLI

### ISSUE THREAD

**Issue by o-marshmallow** [alainfrisch/gen_js_api#61]
Hello, 

I meet a problem when generating an .ml file with my .mli
When implementing a function containing ppx syntax token with `[@@js.custom]`, I get an error compiling the .ml file. Here an example.
In my mli file, I have: 

```
[@@js.custom
  let foo str =
    (Js.Unsafe.global##.myfield := str)
]

```

The generated ml file interprets the `##.` as an infix operator, so it writes in the ml file : 

```
(##. Js.Unsafe.global myfield) := str
```

Then, I get a syntax error when compiling. 
Is there a way to use other packages ppx syntax within the mli file?

**Comment by alainfrisch** [comment]
This is a problem with OCaml's source code printer (pprintast.ml).  You can see it with:

````ocaml
$ ocaml -dsource
        OCaml version 4.04.0

# foo##.bar := ();;

;;(##. foo bar) := ();;
````

Can you send a report on OCaml bug tracker?

**Comment by alainfrisch** [comment]
Never mind, I'll fix it and send a PR directly.

**Comment by alainfrisch** [comment]
See https://github.com/ocaml/ocaml/pull/1243
