### ISSUE TITLE
Would recursive modules be difficult (if possible) to implement?

### ISSUE THREAD

**Issue by ttamttam** [alainfrisch/gen_js_api#67]
I have something like this…

```ocaml  
module rec Contact : sig
   type t
   val get_contact_groups: t -> ContactGroup.t list [@@js.call]
end

and ContactGroup : sig
   type t
   val get_contacts: t -> Contact.t list [@@js.call]
end
```

I solved the problem by getting type Contact.t out of Contact module.
But I do not know if this solution will always be enough?

Best regards

**Comment by alainfrisch** [comment]
I think the workaround is rather general.  You can always lift all the "opaque" type declarations to break recursion at the type level.

As for a direct support, it does not seem out of reach.  The simplest thing to do would be to generate recursive module implementations with the provide signatures, but in your example, these signatures hide the *_to_js/*_of_js functions which are required in the implementation.  One could either extend the internal signatures (on the generated recursive modules), or ask the user to write:

````ocaml
module rec Contact : sig
   type t
   val t_of_js: Ojs.t -> t
   val t_to_js: t -> Ojs.t
   val get_contact_groups: ...
end = ...
````
