### ISSUE TITLE
including modules

### ISSUE THREAD

**Issue by nickbetteridge** [alainfrisch/gen_js_api#69]
I'm having trouble in trying to include modules:

```
type event_phase_type = Capturing_phase [@js 1] | At_target [@js 2] | Bubbling_phase [@js 3] [@@js.enum]

module Event : sig
  type t = private Ojs.t
  val bubbles: t -> bool
  val cancelable: t -> bool
  val current_target: t -> Ojs.t
  val event_phase: t -> event_phase_type
  val prevent_default: t -> unit
  val stop_immediate_propagation: t -> unit
  val stop_propagation: t -> unit
  val target: t -> Ojs.t
  val time_stamp: t -> float
  val type_: t -> string
end

module MouseEvent : sig
  include Event
  type t = Event.t
  val alt_key: t -> bool
  val button: t -> int
  val client_x: t -> int
  val client_y: t -> int
  val ctrl_key: t -> bool
  val detail: t -> int
  val meta_key: t -> bool
  val related_target: t -> Ojs.t
  val screen_x: t -> int
  val screen_y: t -> int
  val shift_key: t -> bool
  val which: t -> int
end
```
I get a ```Error: Cannot parse signature item``` at 'include Event'. I've played around with [%js] without a glimmer of  success. Is there a solution for this?

**Comment by alainfrisch** [comment]
Note that the .mli is not valid in itself: `include Event` refers to a non-existent module *type* `Event`.   A valid OCaml interface would be:

````ocaml
module MouseEvent : sig
  include (module type of Event)
  val alt_key: ...
````

(Note also the removal of the definition for `type t`, which clashes with the imported one.)

But this would have the effect of defining MouseEvent.t as an alias for Event.t, which is not the intention I guess (the methods in MouseEvent should not apply to values of type Event.t).

Here are several approaches to described such hierarchies with gen_js_api:

  - Define MouseEvent.t as an abstract type, with explicit coercion function to/from Event.t.  You can also re-export manually methods for Event in MouseEvent.

  - Flatten the hierarchy, i.e. expose everything in module Event.  I suspect that the OCaml side of your application will introduce some higher-level concepts above the raw DOM APIs, and these layers would be responsible for exposing a more typeful interface to the applicative code.  See e.g. our ocaml-vdom package for such a case.

 - Use OCaml objects and inheritance (https://github.com/LexiFi/gen_js_api/blob/master/CLASSES.md), although I'm personally not a big fan of this approach (it adds a lot of weight to the generated code, and probably some non-negligible runtime overhead).

**Comment by nickbetteridge** [comment]
Excellent - thanks for your time in writing the above - coercion seems the easiest route, but ocaml-vdom looks very interesting. And thanks for correcting the elementary ocaml mistakes! Final thanks for making gen_js_api available - made my life considerably easier.
