### ISSUE TITLE
Polymorphic variant type declaration not supported

### ISSUE THREAD

**Issue by eyyub** [alainfrisch/gen_js_api#70]
Hi,

I'm currently writing a binding using gen_js_api and it seems that this code doesn't compile : 
```ocaml
type t = [`foo | `bar [@js 42] | `Baz] [@@js.enum]
(* Throws this exception : Sum types without js.* attribute not supported in this context. *)

(* While this compile *)
val foo : t -> ([ `a |  `b] [@js.enum]) -> ...
```

After looking at `gen_js_api.ml`, the exception is raised by `get_variant_kind` because `attrs` doesn't contain the attribute `"js.enum"` attached to `t`. In fact the attribute `js.enum` is added to `global_attrs` in [`gen_funs`](https://github.com/LexiFi/gen_js_api/blob/master/src/gen_js_api.ml#L1195) and `get_variant_kind` doesn't look inside.

The workaround I use for now is to match against the return value of `parse_typ` to see if it is a `Variant`, then in this case I manually add the attribute to it, but it's a bit of a hack.

```ocaml
| Some ty, Ptype_abstract ->                                                                                      
      let ty = match parse_typ ~global_attrs ty with                                                                
         | Variant { location; global_attrs; attributes; constrs } ->                                                
             Variant { location; global_attrs; attributes = p.ptype_attributes @ attributes; constrs }               
         | ty -> ty                                                                                                  
       in                                                                                                            
       lazy (js2ml_fun ty), lazy (ml2js_fun ty)
```

I hope I clearly described this issue,

Thank you!

**Comment by sbriais** [comment]
I think the correct way to specify the js.* annotation is:

```ocaml
type t = [`foo | `bar [@js 42] | `Baz] [@js.enum]
```

(note the single @ symbol)
