### ISSUE TITLE
Error: Unresolved internal primitive: %caml_js_opt_meth_call

### ISSUE THREAD

**Issue by Armael** [alainfrisch/gen_js_api#71]
I tried to implement a minimal "hello world" example using gen_js_api: https://github.com/Armael/gen_js_api_helloworld . However, `make` fails at the last step (the `js_of_ocaml` invocation) with:

```
js_of_ocaml --pretty -o test.js +gen_js_api/ojs_runtime.js test.byte
js_of_ocaml: Error: Unresolved internal primitive: %caml_js_opt_meth_call
make: *** [Makefile:7: all] Error 1
```

Am I doing something wrong? If it's a js_of_ocaml bug, it's a bit strange that people seem to manage usin gen_js_api on non-trivial examples, but I can't make it work on a trivial one...

**Comment by hhugo** [comment]
Likely a bug in js_of_ocaml. Can you open an issue with details on how to reproduce.

**Comment by Armael** [comment]
Ok. Done here: https://github.com/ocsigen/js_of_ocaml/issues/573

**Comment by Armael** [comment]
As noticed by @hhugo on https://github.com/ocsigen/js_of_ocaml/issues/573 , the ml code generated by gen_js_api from `val foo : int -> unit` is incorrect. With an explicit `[@@js.global]` annotation, it is correct.

```
val foo : int -> unit
```
produces
```
let (foo : int -> unit) =
  fun x1  -> ignore (Ojs.call (Ojs.int_to_js x1) "foo" [||])
```

while

```
val foo : int -> unit
[@@js.global]
```
produces
```
let (foo : int -> unit) =
  fun x1  -> ignore (Ojs.call Ojs.global "foo" [|(Ojs.int_to_js x1)|])
```

However, if I understand https://github.com/LexiFi/gen_js_api/blob/master/VALUES.md#automatic-binding correctly, the `[@@js.global]` should not be necessary and not providing it should work just the same, which is not the case currently.

**Comment by alainfrisch** [comment]
The relevant case from VALUS.md is:

> If the value is a function with a single argument (named type) t -> unit, then the declaration is assumed to be a [@@js.call] method call, unless a [@js.scope] attribute has been defined in an englobing module. In this latter case, the value is assumed to be a [@@js.global] value.

Do you see something else that would contradict this interpretation?

**Comment by Armael** [comment]
Ah, now I understand the paragraph you are mentionning. I think I may have been confused by "`a single argument (named type) t -> unit`";  and interpreted it as "the type must literally be named `t`", while, if I understand correctly, `t` must be read as a meta-variable here?

Maybe this paragraph could be clarified a bit? Additionally, I don't know why, but when quickly reading through the paragraph, I seem to incorrectly interpret the last sentence as `Otherwise, the value is assumed ...`, with the `Otherwise` referring to the first `If`. Maybe reformulating things could make the whole paragraph a bit clearer.

**Comment by alainfrisch** [comment]
I've changed this section to use greek letters for meta-variables.  If you have some ideas to improve the text, don't hesitate to create a PR!
