### ISSUE TITLE
Build fails with ocaml 4.05-rc1

### ISSUE THREAD

**Issue by aballier** [alainfrisch/gen_js_api#74]
When I build gen_js_api with ocaml 4.05 rc1, I get this error:

```
ocamlc -w +A-4-41-45 -warn-error +8 -I +compiler-libs -o gen_js_api ocamlcommon.cma gen_js_api.mli gen_js_api.ml
File "gen_js_api.ml", line 536, characters 49-60:
Error: This expression has type string Asttypes.loc = string Location.loc
       but an expression was expected of type string
make[1]: *** [Makefile:14: all] Error 2
```

```
$ ocaml --version
The OCaml toplevel, version 4.05.0+rc1
```

**Comment by alainfrisch** [comment]
I've fixed that, created a new release, and submitted it to OPAM.

**Comment by himito** [comment]
Hello,
I have the same problem with ocaml 4.04.0 and trying to compile from the code source [branch master]
Thank you,
Jaime

**Comment by alainfrisch** [comment]
The master branch requires OCaml 4.06.  If you want to use an older version of OCaml, you need to get an older version of gen_js_api as well.

**Comment by himito** [comment]
Thank you very much :)
