### ISSUE TITLE
Request: Create an ocaml string from a javascript array

### ISSUE THREAD

**Issue by martindemello** [alainfrisch/gen_js_api#78]
This is either a feature request or a documentation request...

js_of_ocaml's `typed_array.ml` contains the following:
````
module String = struct
  external of_uint8Array : uint8Array Js.t -> string = "caml_string_of_array"
  let of_arrayBuffer ab =
    let uint8 = new%js uint8Array_fromBuffer ab in
    of_uint8Array uint8
end
````
which is calling `caml_string_of_array` from jsoo's `runtime/mlString.js` to create an ocaml string backed by a javascript array.

Is there any way to do the same thing via gen_js_api?

**Comment by nojb** [comment]
I think declaring
```
external of_uint8Array: Ojs.t -> string = "caml_string_of_array"
```
should work (the `Ojs.t` should be an `Uint8Array`).

**Comment by martindemello** [comment]
i couldn't get that working (syntax error on "external").

**Comment by martindemello** [comment]
got it working by putting the annotation in my ml file rather than the mli file. would be a nice feature for gen_js_api to handle it, but this works for me. thanks!
