### ISSUE TITLE
Release 4.06-compatible version to OPAM

### ISSUE THREAD

**Issue by leviroth** [alainfrisch/gen_js_api#79]
The current OPAM version of gen_js_api requires ocaml-version < "4.06.0". However, the repository itself has been patched to support OCaml 4.06. An update to the OPAM repository would save 4.06 users from having to pin this repository.

**Comment by alainfrisch** [comment]
Thanks for the gentle reminder.  I'd like to sort out #65 and #70 before the next release.

**Comment by alainfrisch** [comment]
Ok, #65 identified a rather serious issue with the current version of js_of_ocaml.  I'll wait for the next version to be released, hopefully this week, to indicate it as a dependency for gen_js_api's OPAM package.

**Comment by alainfrisch** [comment]
https://github.com/ocaml/opam-repository/pull/11610
