### ISSUE TITLE
Calling a binding in a different package throws an Ojs_exn.Error(_)

### ISSUE THREAD

**Issue by nickbetteridge** [alainfrisch/gen_js_api#92]
Hi

I have one package containing a library of a small set of jquery bindings and a test directory. I have a second package containing a library in which there is a dependency on the first library.

The test in the first package can quite happily call ```Jquery.selector string``` in the library. If I make the same call from the second library in the second package then a ```Ojs_exn.Error(_)``` is thrown.

Both packages compile without error using a dune environment and gen_js_api 1.0.5. I can call ```non-binding``` functions in the first library from the second library without error - so the first library is visible to the second library.

There is also another binding in the second library. The test directory in the second package can also call the bindings in the second library without error, but, again, none of the bindings in the first library.

I've spent just over a day on this now and I've run out of ideas on how to fix this - can anyone think of any possible suggestions?

Thanks
Nick

**Comment by nickbetteridge** [comment]
Apols - complete and utter nonsense - works fine

**Comment by nojb** [comment]
Cool, thanks!
