### ISSUE TITLE
[@js.scope ...] ignored by non-functional values

### ISSUE THREAD

**Issue by clembu** [alainfrisch/gen_js_api#93]
Here's my use-case:
Electron has an `app` object/module/thingy with properties, methods, and events.

I want to map those to values in an OCaml module `Electron.App` because `electron.app` is "static": you get it once, and work with it, you never get several of them. So no use for an OCaml-side `app` type or functions that take them.
I'd rather call `App.on_ready f` than any object call or a weird `Electron.App.on app "ready" f`

So here's how I planned things:
```ocaml
module App : sig
  val is_packaged : bool [@@js.global "isPackaged"]
  val app_menu : Menu.t option [@@js.global "applicationMenu"]
  (* ... more stuff ... *)
  val quit : unit -> unit [@@js.global]
  val exit : ?exit_code:int -> unit -> unit [@@js.global]
end [@js.scope "electron.app"]
```
but the generated ml looks like
```ocaml
module App =
  struct
    let (is_packaged : bool) =
      Ojs.bool_of_js (Ojs.get Ojs.global "isPackaged")
    let (app_menu : Menu.t option) =
      Ojs.option_of_js Menu.t_of_js (Ojs.get Ojs.global "applicationMenu")
    (* ... more stuff ... *)
    let (quit : unit -> unit) =
      fun () ->
        ignore
          (Ojs.call (Ojs.get (Ojs.get Ojs.global "electron") "app") "quit"
             [||])
    let (exit : ?exit_code:int -> unit -> unit) =
      fun ?exit_code:x4 ->
        fun () ->
          ignore
            (let x7 = Ojs.get (Ojs.get Ojs.global "electron") "app" in
             Ojs.call (Ojs.get x7 "exit") "apply"
               [|x7;((let x5 = Ojs.new_obj (Ojs.get Ojs.global "Array") [||] in
                      (match x4 with
                       | Some x6 ->
                           ignore (Ojs.call x5 "push" [|(Ojs.int_to_js x6)|])
                       | None -> ());
                      x5))|])
  end
```

The "properties" do not scope to `electron.app`, they stay in global.
Any reason why?

I mean I can still scope them manually and put `electron.app` in the `[@@js.global ...]` attribute but it'd be nice to not have to do that, if I had a lot of properties to map like that

PS: I have that `Menu` module defined with just a type t, and `electron` is in global scope with an unsafe call to `process.mainModule.require` :man_shrugging:

**Comment by alainfrisch** [comment]
The scope is prepended to names which are generated automatically.  If you specify an explicit name, the scope is not applied.  So if you define:

````ocaml
val is_packaged : bool [@@js.global]
````

this should generate the correct code.  If you need to customize the local name, as for `app_menu` (instead of `application_menu`), indeed, you'll need to specify the scope explicitly.

The behavior is debatable, but at least it supports for a fully explicit mode which allows escaping locally from a scope.

**Comment by clembu** [comment]
makes sense. Am I correct in understanding there is a case conversion happening and `is_packaged` will map to `isPackaged`? I doubt it but I want to make sure

**Comment by alainfrisch** [comment]
This is correct (see https://github.com/LexiFi/gen_js_api/blob/master/NAMING.md )

**Comment by clembu** [comment]
I see. Thanks!
